version: '2'

services:
  apache-php:
    #image: php:5.6-apache-stretch
    build: ./docker/webserver
    image: kkk_web
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=my-user
      - MYSQL_PASSWORD=my-password
      - MYSQL_DATABASE=kkk
      - MYSQL_HOST=db