version: '2'

services:
  apache-php:
    build: ./docker/webserver
    image: the_web
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/log/apache2
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=my-user
      - MYSQL_PASSWORD=my-password
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=db